apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vol1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 500Mi
